Add Additional Property-Based Tests for LinkedList
PwPJ/linkedlist pull request #4
Opened 2024-05-31 06:02 UTC by alipourhabibi

Overview:
This pull request adds new Property-Based Tests using testing/quick library.

Changes:
- Add Property-Based Tests for LinkedList

How Has This Been Tested?
- Ran the new tests locally and ensured they pass
- Verified that the existing tests still pass

2024-06-02 07:52 UTC, Iajrdev commented
> Overview: This pull request adds new Property-Based Tests using testing/quick library.
> 
> Changes:
> 
> * Add Property-Based Tests for LinkedList
> 
> How Has This Been Tested?
> 
> * Ran the new tests locally and ensured they pass
> * Verified that the existing tests still pass

@alipourhabibi 
Please rename the test file to Linkedlist_test.go and update the test commands in the README to reflect these latest changes.

2024-06-02 08:09 UTC, alipourhabibi commented
I put all tests in one file and fix the ci

2024-06-02 20:07 UTC, Iajrdev requested changes
Please change highlighted sections in test file

2024-06-02 20:07 UTC, Iajrdev commented on linkedList_test.go
> +	"github.com/leanovate/gopter/prop"
Remove the following imports:
```
"github.com/leanovate/gopter"
"github.com/leanovate/gopter/gen"
"github.com/leanovate/gopter/prop"
```

2024-06-02 20:07 UTC, Iajrdev commented on linkedList_test.go
> +}
The function TestLinkedListProperties based on the `gopter` library it should be removed. We already use the quick package for property-based testing in the same file. To maintain consistency and avoid redundancy please remove this part

2024-06-07 08:59 UTC, alipourhabibi commented
I rebased the commits to one commit

2024-06-07 10:29 UTC, Iajrdev approved these changes
I've reviewed the code and everything looks good to me.

2024-06-07 16:49 UTC, merged